<?php
if (PHP_SAPI !== 'cli') { http_response_code(403); exit; }
require_once __DIR__ . '/../includes/ProjectIntake.php';
require_once __DIR__ . '/../includes/ProjectBusiness.php';
require_once __DIR__ . '/../classes/SimpleXLSX.php';

$templateFile = __DIR__ . '/../订单模板/AI网站定制填写模板.xlsx';
if (!is_file($templateFile)) $templateFile = __DIR__ . '/../订单模板与成本及算法/AI网站定制填写模板.xlsx';
if (is_file($templateFile)) {
    $templateRows = SimpleXLSX::parse($templateFile);
    if (count($templateRows[0] ?? []) !== 14 || ($templateRows[0][10] ?? '') !== '域名使用（写是/否）') {
        fwrite(STDERR, "原始 AI 网站定制 XLSX 模板未能正确解析\n");
        exit(1);
    }
} else {
    fwrite(STDERR, "原始 AI 网站定制 XLSX 模板当前不在工作区，跳过该文件解析检查\n");
}

$pdo = db();
$pdo->beginTransaction();
try {
    // 只用本测试自建的成本模板，避免库里已有的 .com 模板让自动匹配变成“不唯一”。
    $pdo->exec('UPDATE project_cost_templates SET is_active=0');
    $adminId = (int)$pdo->query('SELECT id FROM admins ORDER BY id LIMIT 1')->fetchColumn();
    $employeeId = (int)$pdo->query('SELECT id FROM employees ORDER BY id LIMIT 1')->fetchColumn();
    if (!$adminId || !$employeeId) throw new RuntimeException('测试需要已有财务管理员及合作人员');
    $no = 'INTAKE-' . bin2hex(random_bytes(6));
    $pdo->prepare("INSERT INTO project_cost_templates (category,name,specification,unit,cost_kind,price,requires_proof,auto_approve) VALUES ('domain','.com域名','1年','年','annual',75,0,1),('server','基础VPS','2核4G/1年','年','annual',480,0,1)")->execute();
    $domainId = (int)$pdo->query("SELECT id FROM project_cost_templates WHERE name='.com域名' ORDER BY id DESC LIMIT 1")->fetchColumn();
    $domain = ps_intake_template($domainId, 'domain');
    $server = ps_intake_templates('server');
    $suggested = ps_intake_domain_suggestion('客户域名 example.com', [$domain]);
    if (!$suggested || (int)$suggested['id'] !== $domainId) throw new RuntimeException('Excel .com 域名未正确匹配一年模板');
    if (ps_intake_domain_suggestion('只写：是', [$domain]) !== null) throw new RuntimeException('仅写是不能自动推断 .com');
    $pdo->prepare("INSERT INTO project_orders (order_no,order_date,project_type,contract_amount) VALUES (?,CURDATE(),'AI网站定制',6800)")->execute([$no]);
    $orderId = (int)$pdo->lastInsertId();
    ps_intake_participants($orderId, ['technical' => [$employeeId => ['id' => $employeeId, 'role' => '前端']], 'customer_service' => []]);
    $actor = ['type' => 'admin', 'id' => $adminId, 'employee_id' => null, 'role' => 'finance'];
    ps_intake_save_resources($orderId, 'manual', null, $domain, $server[count($server) - 1], 120);
    ps_intake_add_template_cost($orderId, $domain, $actor, '测试手动域名');
    ps_intake_add_template_cost($orderId, $server[count($server) - 1], $actor, '测试服务器');
    try {
        ps_approve_order($orderId, $actor, '2098-05');
        throw new RuntimeException('报备 SSL 未补成本也允许生成项目分成');
    } catch (RuntimeException $expected) {
        if (strpos($expected->getMessage(), 'SSL 报备成本') === false) throw $expected;
    }
    $q = $pdo->prepare('SELECT category,unit_price,amount,review_status,template_version FROM project_costs WHERE order_id=? ORDER BY id');
    $q->execute([$orderId]);
    $costs = $q->fetchAll();
    if (count($costs) !== 2 || (float)$costs[0]['amount'] !== 75.0 || (float)$costs[1]['amount'] !== 480.0 || $costs[0]['review_status'] !== 'approved') throw new RuntimeException('标准成本没有按模板价格自动入账');
    $participantCount = $pdo->prepare('SELECT COUNT(*) FROM project_participants WHERE order_id=? AND employee_id=?');
    $participantCount->execute([$orderId, $employeeId]);
    if ((int)$participantCount->fetchColumn() !== 1) throw new RuntimeException('手动录入参与人没有正确绑定');
    $_SESSION['admin_id'] = $adminId;
    $_SERVER['REQUEST_METHOD'] = 'GET';
    $_SERVER['SCRIPT_NAME'] = '/project/index.php';
    ob_start(); include __DIR__ . '/../project/index.php'; $manualHtml = ob_get_clean();
    if (strpos($manualHtml, '手动录入订单') === false || strpos($manualHtml, '无需域名') === false || strpos($manualHtml, '拖拽上传 Excel') === false) throw new RuntimeException('订单录入页未正常渲染');
    $employeeNameQuery = $pdo->prepare('SELECT name FROM employees WHERE id=?');
    $employeeNameQuery->execute([$employeeId]);
    $employeeName = $employeeNameQuery->fetchColumn();
    $shopName = (string)$pdo->query('SELECT name FROM shops ORDER BY sort,id LIMIT 1')->fetchColumn();
    if ($shopName === '') throw new RuntimeException('测试需要已有店铺');
    $csv = tmpfile();
    fputcsv($csv, ['日期','店铺','业务','付款昵称','订单编号','售价','状态(填已完成/未完成)','备注（写客户电话或者微信）','客服','前端（技术）','域名使用（写是/否）','SSL证书使用（写真实成本）','后端','填一下域名或者空间']);
    $importNo = $no . '-CSV';
    fputcsv($csv, [date('Y-m-d'),$shopName,'AI网站定制','测试客户',$importNo,'6800','已完成','','',$employeeName,'是','0','无','客户域名 example.com']);
    $unresolvedNo = $no . '-UNRESOLVED';
    fputcsv($csv, [date('Y-m-d'),$shopName,'AI网站定制','测试客户',$unresolvedNo,'6800','已完成','','',$employeeName,'是','0','无','只写使用域名']);
    fflush($csv);
    $csvPath = stream_get_meta_data($csv)['uri'];
    $_SERVER['SCRIPT_NAME'] = '/project/import.php';
    $_SERVER['REQUEST_METHOD'] = 'POST';
    $_POST = ['csrf' => ps_csrf_token(), 'action' => 'preview'];
    $_FILES = ['file' => ['name' => 'test.csv', 'tmp_name' => $csvPath, 'error' => UPLOAD_ERR_OK, 'size' => filesize($csvPath)]];
    ob_start(); include __DIR__ . '/../project/import.php'; $importHtml = ob_get_clean();
    if (strpos($importHtml, '拖拽 Excel 到这里') === false || strpos($importHtml, $importNo) === false) throw new RuntimeException('Excel 拖拽上传预览页未正常渲染');
    $previewRow = $_SESSION['project_import_preview'][0] ?? null;
    if (!$previewRow || (int)$previewRow['domain_template_id'] !== $domainId || $previewRow['status'] !== '可导入') throw new RuntimeException('Excel 域名提示未自动匹配标准成本');
    $unresolvedRow = $_SESSION['project_import_preview'][1] ?? null;
    if (!$unresolvedRow || $unresolvedRow['status'] !== '需选择域名模板' || (int)$unresolvedRow['domain_template_id'] !== 0) throw new RuntimeException('仅写使用域名的订单不应自动扣 .com 成本');
    $_POST = ['csrf' => ps_csrf_token(), 'action' => 'commit', 'domain_choice' => [2 => (string)$domainId]];
    $_FILES = [];
    ob_start(); include __DIR__ . '/../project/import.php'; $committedHtml = ob_get_clean();
    if (strpos($committedHtml, '已导入 1 个订单') === false) throw new RuntimeException('Excel 核对后提交失败');
    $importQuery = $pdo->prepare('SELECT id,receipt_amount FROM project_orders WHERE order_no=?');
    $importQuery->execute([$importNo]);
    $importOrder = $importQuery->fetch();
    if (!$importOrder || (float)$importOrder['receipt_amount'] !== 0.0) throw new RuntimeException('Excel 售价不应自动确认为实收');
    $importCost = $pdo->prepare("SELECT amount FROM project_costs WHERE order_id=? AND category='domain'");
    $importCost->execute([$importOrder['id']]);
    if ((float)$importCost->fetchColumn() !== 75.0) throw new RuntimeException('Excel 域名成本未自动写入模板价');
    $unresolvedQuery = $pdo->prepare('SELECT COUNT(*) FROM project_orders WHERE order_no=?');
    $unresolvedQuery->execute([$unresolvedNo]);
    if ((int)$unresolvedQuery->fetchColumn() !== 0) throw new RuntimeException('未选域名模板的 Excel 行被错误导入');
    $resourceQuery = $pdo->prepare('SELECT domain_mode,domain_template_id,ssl_expected_amount FROM project_order_resources WHERE order_id=?');
    $resourceQuery->execute([$importOrder['id']]);
    $resource = $resourceQuery->fetch();
    if (!$resource || $resource['domain_mode'] !== 'template' || (int)$resource['domain_template_id'] !== $domainId || $resource['ssl_expected_amount'] !== null) throw new RuntimeException('Excel 资源选择快照未正确保存');
    $_POST = ['csrf' => ps_csrf_token(), 'action' => 'preview', 'business' => 'AI网站定制'];
    $_FILES = ['file' => ['name' => 'test.csv', 'tmp_name' => $csvPath, 'error' => UPLOAD_ERR_OK, 'size' => filesize($csvPath)]];
    ob_start(); include __DIR__ . '/../project/import.php'; ob_end_clean();
    $sameOrderPreview = $_SESSION['project_import_preview'][0] ?? null;
    if (!$sameOrderPreview || !$sameOrderPreview['base_valid'] || $sameOrderPreview['status'] !== '补充已有订单' || !$sameOrderPreview['resource_locked']) throw new RuntimeException('相同订单号未显示为补充已有订单');
    $_POST = ['csrf' => ps_csrf_token(), 'action' => 'commit', 'business' => 'AI网站定制'];
    $_FILES = [];
    ob_start(); include __DIR__ . '/../project/import.php'; ob_end_clean();
    $sameOrderCount = $pdo->prepare('SELECT COUNT(*) FROM project_orders WHERE order_no=?');
    $sameOrderCount->execute([$importNo]);
    if ((int)$sameOrderCount->fetchColumn() !== 1) throw new RuntimeException('重复上传创建了第二张订单');
    $importCost->execute([$importOrder['id']]);
    if (count($importCost->fetchAll()) !== 1) throw new RuntimeException('重复上传重复计入标准域名成本');
    $conflictCsv = tmpfile();
    $conflictHeaders = ps_business_import_headers('AI网站定制');
    $conflictData = array_fill_keys($conflictHeaders, '');
    $conflictData['日期'] = date('Y-m-d');
    $conflictData['店铺'] = $shopName;
    $conflictData['业务'] = 'AI网站定制';
    $conflictData['订单编号'] = $importNo;
    $conflictData['售价'] = '9900';
    $conflictData['状态(填已完成/未完成)'] = '已完成';
    $conflictData['前端（技术）'] = $employeeName;
    fputcsv($conflictCsv, $conflictHeaders);
    fputcsv($conflictCsv, array_values($conflictData));
    fflush($conflictCsv);
    $conflictPath = stream_get_meta_data($conflictCsv)['uri'];
    $_POST = ['csrf' => ps_csrf_token(), 'action' => 'preview', 'business' => 'AI网站定制'];
    $_FILES = ['file' => ['name' => 'conflict.csv', 'tmp_name' => $conflictPath, 'error' => UPLOAD_ERR_OK, 'size' => filesize($conflictPath)]];
    ob_start(); include __DIR__ . '/../project/import.php'; ob_end_clean();
    $conflictPreview = $_SESSION['project_import_preview'][0] ?? null;
    if (!$conflictPreview || $conflictPreview['base_valid'] || strpos($conflictPreview['error'], '售价不一致') === false) throw new RuntimeException('上传售价与原单冲突时未要求财务核对');
    fclose($conflictCsv);
    // 部门表常见的空日期/空订单号：可在预览中补填，不必修改原 Excel 或重新上传。
    $repairCsv = tmpfile();
    $repairHeaders = ps_business_import_headers('小程序开发');
    fputcsv($repairCsv, $repairHeaders);
    $repairNos = [$no . '-REPAIR-1', $no . '-REPAIR-2', $no . '-REPAIR-3'];
    foreach ([['2026-09-14', $repairNos[0]], ['', $repairNos[1]], ['2026-09-17', '']] as $index => [$rowDate, $rowNo]) {
        $data = array_fill_keys($repairHeaders, '');
        $data['日期'] = $rowDate; $data['店铺'] = $shopName; $data['业务'] = '小程序开发';
        $data['订单编号'] = $rowNo; $data['售价'] = (string)(500 + $index * 100);
        $data['状态(填已完成/未完成)'] = '已完成'; $data['制作技术'] = $employeeName; $data['订单类型'] = '定制';
        fputcsv($repairCsv, array_values($data));
    }
    fflush($repairCsv);
    $repairPath = stream_get_meta_data($repairCsv)['uri'];
    $_POST = ['csrf' => ps_csrf_token(), 'action' => 'preview', 'business' => '小程序开发'];
    $_FILES = ['file' => ['name' => 'repair.csv', 'tmp_name' => $repairPath, 'error' => UPLOAD_ERR_OK, 'size' => filesize($repairPath)]];
    ob_start(); include __DIR__ . '/../project/import.php'; $repairHtml = ob_get_clean();
    $repairPreview = $_SESSION['project_import_preview'] ?? [];
    if (count($repairPreview) !== 3 || empty($repairPreview[0]['base_valid']) || !empty($repairPreview[1]['base_valid']) || !empty($repairPreview[2]['base_valid'])) throw new RuntimeException('缺日期/缺订单号行没有正确区分合格行');
    if (strpos($repairHtml, '应用补填并重新核对') === false || strpos($repairHtml, '先导入 1 行合格订单') === false) throw new RuntimeException('预览页没有提供补填与先导入入口');
    $repairFileId = (int)($_SESSION['project_import_file'] ?? 0);
    $_POST = ['csrf' => ps_csrf_token(), 'action' => 'commit', 'business' => '小程序开发'];
    $_FILES = [];
    ob_start(); include __DIR__ . '/../project/import.php'; $partialHtml = ob_get_clean();
    if (strpos($partialHtml, '已导入 1 个订单') === false || count($_SESSION['project_import_preview'] ?? []) !== 2) throw new RuntimeException('先导入合格行后没有保留待修正行');
    $_POST = ['csrf' => ps_csrf_token(), 'action' => 'repair_preview', 'business' => '小程序开发', 'fix_date' => [3 => '2026-09-14'], 'fix_order_no' => [4 => $repairNos[2]]];
    $_FILES = [];
    ob_start(); include __DIR__ . '/../project/import.php'; ob_end_clean();
    $repairPreview = $_SESSION['project_import_preview'] ?? [];
    if (count($repairPreview) !== 2 || count(array_filter($repairPreview, function ($r) { return !empty($r['base_valid']); })) !== 2 || $repairPreview[0]['order_date'] !== '2026-09-14' || $repairPreview[1]['order_no'] !== $repairNos[2]) throw new RuntimeException('预览内补填没有重新核对通过');
    $_POST = ['csrf' => ps_csrf_token(), 'action' => 'commit', 'business' => '小程序开发'];
    ob_start(); include __DIR__ . '/../project/import.php'; ob_end_clean();
    $repairQuery = $pdo->prepare('SELECT COUNT(*) FROM project_orders WHERE order_no IN (?,?,?)');
    $repairQuery->execute($repairNos);
    if ((int)$repairQuery->fetchColumn() !== 3) throw new RuntimeException('补填后未导入全部三笔订单');
    $fileCount = $pdo->prepare('SELECT imported_count,skipped_count FROM project_import_files WHERE id=?'); $fileCount->execute([$repairFileId]);
    $fileStats = $fileCount->fetch();
    if ((int)$fileStats['imported_count'] !== 3 || (int)$fileStats['skipped_count'] !== 0) throw new RuntimeException('分两次导入时原始表格统计未累计');
    fclose($repairCsv);
    if (ps_business_fallback('设计客服') !== '设计' || ps_business_fallback('定制前端') !== 'AI网站定制') throw new RuntimeException('部门默认业务匹配错误');
    $designCsv = tmpfile();
    $designHeaders = ps_business_import_headers('设计');
    if (in_array('域名使用（写是/否）', $designHeaders, true) || !in_array('设计内容', $designHeaders, true)) throw new RuntimeException('设计业务模板字段错误');
    fputcsv($designCsv, $designHeaders);
    $designNo = $no . '-DESIGN';
    $designData = array_fill_keys($designHeaders, '');
    $designData['日期'] = date('Y-m-d');
    $designData['店铺'] = $shopName;
    $designData['业务'] = '设计';
    $designData['订单编号'] = $designNo;
    $designData['售价'] = '350';
    $designData['状态(填已完成/未完成)'] = '已完成';
    $designData['客服'] = $employeeName;
    $designData['设计内容'] = '品牌海报';
    $designData['交付文件 / 规格'] = 'PNG';
    fputcsv($designCsv, array_values($designData));
    fflush($designCsv);
    $designPath = stream_get_meta_data($designCsv)['uri'];
    $_POST = ['csrf' => ps_csrf_token(), 'action' => 'preview', 'business' => '设计'];
    $_FILES = ['file' => ['name' => 'design.csv', 'tmp_name' => $designPath, 'error' => UPLOAD_ERR_OK, 'size' => filesize($designPath)]];
    ob_start(); include __DIR__ . '/../project/import.php'; ob_end_clean();
    $designPreview = $_SESSION['project_import_preview'][0] ?? null;
    if (!$designPreview || $designPreview['project_type'] !== '设计' || $designPreview['details']['design_item'] !== '品牌海报' || $designPreview['domain_mode'] !== 'none') throw new RuntimeException('设计业务专属导入预览错误');
    $_POST = ['csrf' => ps_csrf_token(), 'action' => 'commit', 'business' => '设计'];
    $_FILES = [];
    ob_start(); include __DIR__ . '/../project/import.php'; ob_end_clean();
    $designQuery = $pdo->prepare('SELECT o.id,d.details_json FROM project_orders o JOIN project_order_details d ON d.order_id=o.id WHERE o.order_no=?');
    $designQuery->execute([$designNo]);
    $designOrder = $designQuery->fetch();
    if (!$designOrder || json_decode($designOrder['details_json'], true)['design_item'] !== '品牌海报') throw new RuntimeException('设计业务专属信息未保存');
    $resourceQuery->execute([$designOrder['id']]);
    if ($resourceQuery->fetch()) throw new RuntimeException('设计业务错误创建了域名资源记录');
    $otherEmployeeId = (int)$pdo->query('SELECT e.id FROM employees e LEFT JOIN project_users u ON u.employee_id=e.id WHERE e.id<>' . $employeeId . ' AND u.id IS NULL ORDER BY e.id LIMIT 1')->fetchColumn();
    if (!$otherEmployeeId) throw new RuntimeException('权限测试需要第二名合作人员');
    $pdo->prepare("INSERT INTO project_users (employee_id,username,password_hash,role) VALUES (?,?,?,'technical')")
        ->execute([$otherEmployeeId, 'intake-test-' . bin2hex(random_bytes(5)), password_hash('test-password-123', PASSWORD_DEFAULT)]);
    unset($_SESSION['admin_id']);
    $_SESSION['project_user_id'] = (int)$pdo->lastInsertId();
    $pdo->prepare('INSERT INTO project_user_businesses (user_id,business_name,is_default) VALUES (?,\'AI网站定制\',1)')->execute([$_SESSION['project_user_id']]);
    $_POST = ['csrf' => ps_csrf_token(), 'action' => 'preview', 'business' => 'AI网站定制'];
    $_FILES = ['file' => ['name' => 'test.csv', 'tmp_name' => $csvPath, 'error' => UPLOAD_ERR_OK, 'size' => filesize($csvPath)]];
    ob_start(); include __DIR__ . '/../project/import.php'; ob_end_clean();
    $staffPreview = $_SESSION['project_import_preview'][0] ?? null;
    if (!$staffPreview || !empty($staffPreview['base_valid']) || (strpos($staffPreview['error'], '未写本人') === false && strpos($staffPreview['error'], '本人尚未被关联') === false)) throw new RuntimeException('技术错误地可导入他人订单');
    unset($_SESSION['project_user_id'], $_SESSION['project_import_preview'], $_SESSION['project_import_actor'], $_SESSION['project_import_business']);
    fclose($csv);
    fclose($designCsv);
    $pdo->rollBack();
    echo "手动录入、标准域名成本及拖拽导入页面验证通过；测试数据已回滚\n";
} catch (Throwable $e) {
    if ($pdo->inTransaction()) $pdo->rollBack();
    fwrite(STDERR, $e->getMessage() . "\n");
    exit(1);
}
