<?php
require_once __DIR__.'/../includes/ProjectBatchFill.php';
$n=0;
function check($name,$actual,$expected){global $n;$n++;if($actual!==$expected)throw new RuntimeException($name.': '.json_encode($actual,JSON_UNESCAPED_UNICODE));}
function reject($name,$fn){global $n;$n++;try{$fn();}catch(RuntimeException $e){return;}throw new RuntimeException($name.' did not reject');}
check('no contact',pr_has_contact([]),false);
check('wechat only complete',pr_has_contact(['phone_hash'=>'','wechat_hash'=>'wx']),true);
check('phone only complete',pr_has_contact(['phone_hash'=>'p','wechat_hash'=>'']),true);
check('both complete',pr_has_contact(['phone_hash'=>'p','wechat_hash'=>'wx']),true);
check('wechat accepted',pr_wechat(' customer_wechat '),'customer_wechat');
check('blank wechat',pr_wechat(''),'');
reject('wechat rejects URL',function(){pr_wechat('https://example.com');});
reject('wechat too long',function(){pr_wechat(str_repeat('a',61));});
check('international phone',pr_phone('+1 (415) 555-0123'),'+14155550123');
check('mainland phone',pr_phone('+86 13800138000'),'13800138000');
reject('wechat not a phone',function(){pr_phone('overseas_wechat');});
reject('no arbitrary contact',function(){pr_phone('不方便填写');});
$map=pbf_map(['订单号','业务类型','海外客户微信号','客户域名','服务器到期日','售价','分成']);
check('money excluded',isset($map['售价']),false);
check('division excluded',isset($map['分成']),false);
$row=pbf_parse_row(['3316999980169003684','网站定制','overseas_client','Example.com','2027-09-01','1000','200'],$map);
check('order preserved as string',$row['order_no'],'3316999980169003684');
check('business alias',$row['business'],'AI网站定制');
check('wechat parsed',$row['values']['wechat'],'overseas_client');
check('domain canonical',$row['values']['domain'],'example.com');
check('expiry parsed',$row['values']['server_expiry'],'2027-09-01');
check('no financial values',count($row['values']),3);
$bad=pbf_parse_row(['123','网站定制','https://bad','valid.com','bad-date'],$map);
check('invalid fields listed',count($bad['issues']),2);
check('valid fields retained',$bad['values'],['domain'=>'valid.com']);
$ow=pbf_parse_row(['123','客户自有'],pbf_map(['订单号','域名归属']));
check('owner needs note',isset($ow['values']['owner']),false);
check('owner missing note listed',count($ow['issues']),1);
check('blank fill',pbf_merge_value('','new'),'fill');
check('null fill',pbf_merge_value(null,'new'),'fill');
check('same no-op',pbf_merge_value('new','new'),'same');
check('different no overwrite',pbf_merge_value('old','new'),'conflict');
check('blank no clear',pbf_merge_value('old',''),'skip');
check('estimated actual allowed',pbf_merge_value('2027-01-01','2027-02-01',true),'fill');
check('same estimate confirmed',pbf_merge_value('2027-01-01','2027-01-01',true),'fill');
check('actual date immutable',pbf_merge_value('2027-01-01','2027-02-01',false),'conflict');
$o=['id'=>1,'order_no'=>'123','project_type'=>'网站模板'];
$item=['id'=>2,'resource_type'=>'domain','resource_name'=>'old.com','expires_on'=>'2027-09-01','expiry_source'=>'imported','status'=>'active','owner'=>'ours','phone_hash'=>'','wechat_hash'=>'','sms_enabled'=>0];
$plan=pbf_plan($o,[$item],['values'=>['domain'=>'new.com','domain_expiry'=>'2027-10-01','wechat'=>'customer_wx']]);
check('resource conflicts separate',count($plan['issues']),2);
check('wechat still fillable',array_column($plan['changes'],'key'),['wechat']);
$plan=pbf_plan($o,[$item],['values'=>['domain'=>'old.com','domain_expiry'=>'2027-09-01']]);
check('same fields no changes',count($plan['changes']),0);
check('same fields listed',count($plan['same']),2);
$many=[$item,$item];$many[1]['id']=3;$many[1]['resource_name']='second.com';
reject('multiple expiry resources ambiguous',function()use($many){pbf_resource($many,'domain',[]);});
check('exact name picks right resource',pbf_resource($many,'domain',['domain'=>'second.com'])['id'],3);
$item['status']='closed';
$plan=pbf_plan($o,[$item],['values'=>['domain_expiry'=>'2028-09-01']]);
check('closed does not reopen',count($plan['changes']),0);
check('closed warning',count($plan['issues']),1);
$item['status']='active';$item['resource_name']='';$item['expires_on']='2027-09-01';$item['expiry_source']='estimated';
$plan=pbf_plan($o,[$item],['values'=>['domain_expiry'=>'2027-09-02']]);
check('estimate fill plan',array_column($plan['changes'],'key'),['domain_expiry']);
$sheets=['订单资料补全'=>[['订单号','海外客户微信号'],['123','wx_test'],['示例123','ignore']],'填写说明'=>[['填写说明'],['不应导入']]];
check('notes and examples ignored',count(pbf_parse_sheets($sheets)),1);
reject('no header does not invent order',function(){pbf_parse_sheets(['x'=>[['说明'],['123','wx']]]);});
$message='';try{pbf_parse_sheets(['订单资料补全'=>[['订单ID','订单号','海外客户微信号'],['1','123','']]]);}catch(RuntimeException $e){$message=$e->getMessage();}
check('blank template feedback explains no changes',strpos($message,'资料列还是空白')!==false && strpos($message,'没有被改动')!==false,true);
$message='';try{pbf_parse_sheets(['未知表'=>[['说明'],['123','wx']]]);}catch(RuntimeException $e){$message=$e->getMessage();}
check('unknown template feedback offers correct template',strpos($message,'未识别到')!==false && strpos($message,'下载本页补全模板')!==false,true);
$onlyWx=['status'=>'active','sms_enabled'=>1,'phone_hash'=>'','wechat_hash'=>'wx','resource_name'=>'example.com','expires_on'=>'2026-10-18'];
check('wechat never SMS',pr_reminder_day($onlyWx,'2026-10-08'),null);
$server=['resource_type'=>'server','status'=>'active','owner'=>'ours','phone_hash'=>'phone','wechat_hash'=>'','resource_name'=>'','expires_on'=>'2027-09-01','expiry_source'=>'manual'];
$cert=array_merge($server,['resource_type'=>'miniapp_certification','resource_name'=>'小程序','expiry_source'=>'estimated']);
check('certification missing date remains downloadable',pbf_missing_fields(['project_type'=>'小程序开发'],[$server,$cert]),['微信认证到期日']);
$filing=array_merge($server,['resource_type'=>'icp','expires_on'=>null]);
check('existing filing missing date remains downloadable',pbf_missing_fields(['project_type'=>'网站模板','domain_mode'=>'none'],[$server,$filing]),['备案到期日']);
$cert['resource_name']='';$cert['expiry_source']='manual';
check('certification missing name remains downloadable',pbf_missing_fields(['project_type'=>'小程序开发'],[$server,$cert]),['小程序名称']);
$owned=array_merge($server,['resource_type'=>'domain','status'=>'closed','owner'=>'customer','expires_on'=>null]);
check('customer-owned closed domain stays exempt',pbf_missing_fields(['project_type'=>'网站模板','domain_mode'=>'pending'],[$owned]),[]);
echo "PASS $n batch/contact pure checks\n";
